### ISSUE TITLE
`ReferenceError: response is not defined` error when compiling template

### ISSUE THREAD

**Issue by johngallagher** [posthtml/posthtml-fetch#75]
I'm getting an error when I use this plugin in conjunction with `posthtml-modules` and `posthtml-expressions`.

## The command

```bash
yarn run posthtml -c posthtml_config.json
```

## The error

```bash

yarn run v1.22.19
warning ../package.json: No license field
$ /Users/johngallagher/Dropbox/Projects/driveways__west_midland__england/node_modules/.bin/posthtml -c posthtml_config.json
SyntaxError: ReferenceError: response is not defined
    at placeholders (/Users/johngallagher/Dropbox/Projects/driveways__west_midland__england/node_modules/posthtml-expressions/lib/placeholders.js:62:19)
    at /Users/johngallagher/Dropbox/Projects/driveways__west_midland__england/node_modules/posthtml-expressions/lib/index.js:198:14
    at Array.reduce (<anonymous>)
    at walk (/Users/johngallagher/Dropbox/Projects/driveways__west_midland__england/node_modules/posthtml-expressions/lib/index.js:185:27)
    at /Users/johngallagher/Dropbox/Projects/driveways__west_midland__england/node_modules/posthtml-expressions/lib/index.js:229:22
    at Array.reduce (<anonymous>)
    at walk (/Users/johngallagher/Dropbox/Projects/driveways__west_midland__england/node_modules/posthtml-expressions/lib/index.js:185:27)
    at /Users/johngallagher/Dropbox/Projects/driveways__west_midland__england/node_modules/posthtml-expressions/lib/index.js:166:9
    at err (/Users/johngallagher/Dropbox/Projects/driveways__west_midland__england/node_modules/posthtml/lib/index.js:219:34)
    at tryCatch (/Users/johngallagher/Dropbox/Projects/driveways__west_midland__england/node_modules/posthtml/lib/index.js:300:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## My `package.json`

```json
{
  "name": "***",
  "version": "1.0.0",
  "main": "index.js",
  "repository": "***",
  "author": "John Gallagher",
  "license": "MIT",
  "dependencies": {
    "@trycourier/courier": "^4.1.0",
    "posthtml": "^0.16.6",
    "posthtml-cli": "^0.10.0",
    "posthtml-modules": "^0.9.0",
    "posthtml-fetch": "^2.2.0",
    "posthtml-expressions": "^1.11.0"
  }
}
```

Yarn: 1.22.19

## My config

```json
{
  "input": "public/[redacted]/near-me/index.html",
  "output": "public_output",
  "allInOutput": true,
  "plugins": {
    "posthtml-modules": {
      "root": ".",
      "initial": true,
      "attributeAsLocals": true,
      "locals": {},
    "posthtml-fetch": {},
    "posthtml-expressions": {}
  }
}
```

## My template

```html
<remote url="https://jsonplaceholder.typicode.com/users/1">
  {{ response.name }}'s username is {{ response.username }}
</remote>
```

Any ideas what I'm doing wrong?

**Comment by johngallagher** [comment]
Ah - I've worked it out - `posthtml-fetch` can't handle `fetch` blocks within `module`. Any ideas how I'd fix it so I can get it working with the HTML modules I define from `posthtml-module`? Thanks!

**Comment by johngallagher** [comment]
This is because I'm using `posthtml-cli`. I need to use the option `plugins` - https://github.com/posthtml/posthtml-modules#plugins to define `posthtml-fetch` so it can run this plugin in the context of my modules.

But I the JSON config of `posthtml-cli` won't accept functions in JSON config... any ideas how to do this?

**Comment by Scrum** [comment]
Maybe you should use `posthtml.config.js` to be able to add plugins
